import os

KEYSTONE_USERNAME = os.getenv('KEYSTONE_USERNAME')
KEYSTONE_PASSWORD = os.getenv('KEYSTONE_PASSWORD')
KEYSTONE_TENANT_NAME = os.getenv('KEYSTONE_TENANT_NAME')
KEYSTONE_AUTH_URL = os.getenv('KEYSTONE_AUTH_URL')
